eaac_proj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('members/', include('members.urls')),
    path('admin/', admin.site.urls),
]

members/urls.py
from django.urls import path

from . import views

app_name = 'members_app'

urlpatterns = [
    path('', views.list_active, name='list_active'),
    path('list_all/', views.list_all, name='list_all'),
    path('list_all_grid/', views.list_all_grid, name='list_all_grid'),
    path('list_board/', views.list_board, name='list_board'),
    path('list_active/', views.list_active, name='list_active'),
    path('list_inactive/', views.list_inactive, name='list_inactive'),
    path('needs_review/', views.needs_review, name='needs_review'),
    path('show_member_info/<int:member_id>/', views.show_member_info, name='show_member_info'),
    path('edit_member_info/<int:member_id>/', views.edit_member_info, name='edit_member_info'),
    path('save_member_info/', views.save_member_info, name='save_member_info'),
    path('search/', views.search_results, name='search_results'),
]

members/models.py
from django.db import models
from django.contrib.auth.models import User

def all_member_count(user):
    number_of_all_members = Member.objects.count()
    return number_of_all_members
User.add_to_class('all_member_count', all_member_count)

def board_member_count(user):
    number_of_board_members = Member.objects.filter(board_member=True).count()
    return number_of_board_members
User.add_to_class('board_member_count', board_member_count)

def active_member_count(user):
    number_of_active_members = Member.objects.filter(membership_status='Active').count()
    return number_of_active_members
User.add_to_class('active_member_count', active_member_count)

def inactive_member_count(user):
    number_of_inactive_members = Member.objects.filter(membership_status='Inactive').count()
    return number_of_inactive_members
User.add_to_class('inactive_member_count', inactive_member_count)

def needs_review_count(user):
    number_of_needs_review = Member.objects.filter(needs_review=1).count()
    return number_of_needs_review
User.add_to_class('needs_review_count', needs_review_count)

class Member(models.Model):
    name1               = models.CharField(max_length=100)
    sort_by             = models.CharField(max_length=100)
    byline              = models.CharField(max_length=200, blank=True)
    name2               = models.CharField(max_length=100, blank=True)
    note                = models.CharField(max_length=100, blank=True)
    phone_number1       = models.CharField(max_length=100, blank=True)
    phone_number2       = models.CharField(max_length=100, blank=True)
    address1            = models.CharField(max_length=200, blank=True)
    address2            = models.CharField(max_length=200, blank=True)
    city                = models.CharField(max_length=100, blank=True)
    state               = models.CharField(max_length=30, blank=True)
    postal_code         = models.CharField(max_length=10, blank=True)
    email1              = models.CharField(max_length=200, blank=True)
    email2              = models.CharField(max_length=200, blank=True)
    ACTIVE = 'Active'
    INACTIVE = 'Inactive'
    MEMBERSHIP_STATUS_CHOICES = [
        (ACTIVE, 'Active'),
        (INACTIVE, 'Inactive'),
    ]
    membership_status = models.CharField(
        max_length=20,
        choices=MEMBERSHIP_STATUS_CHOICES,
        default=ACTIVE,
        blank=True,
    )
    SUPPORTER = 'Supporter'
    CONTRIBUTOR = 'Contributor'
    ADVOCATE = 'Advocate'
    HONORARY = 'Honorary'
    PAM_STAFF = 'PAM staff'
    MEMBER_TYPE_CHOICES = [
        (SUPPORTER, 'Supporter'),
        (CONTRIBUTOR, 'Contributor'),
        (ADVOCATE, 'Advocate'),
        (HONORARY, 'Honorary'),
        (PAM_STAFF, 'PAM staff'),
    ]
    board_member = models.BooleanField(default=False)
    membership_type = models.CharField(
        max_length=20,
        choices=MEMBER_TYPE_CHOICES,
        default=SUPPORTER,
        blank=True,
    )
    role                = models.CharField(max_length=200, blank=True)
    directory_optout    = models.BooleanField(default=False)
    needs_review        = models.BooleanField(default=False)
    reason_for_review   = models.CharField(max_length=200, blank=True)

    class Meta:
        ordering = ['sort_by',]

    def __str__(self):
        output = self.name1
        if self.name2 != '':
            output += ' and ' + self.name2
        return output

members/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from functools import reduce
from .models import Member
from itertools import chain

# def index(request):
#     return HttpResponse("Hello world!")

@login_required
def list_all(request):
    all_members = Member.objects.all()
    paginator = Paginator(all_members, 10)
    page_number = request.GET.get('page')
    members = paginator.get_page(page_number)
    context = {
        'members': members,
    }
    return render(request, 'members/output.html', context)

@login_required
def list_all_grid(request):
    members = Member.objects.all()
    context = {
        'members': members,
    }
    return render(request, 'members/grid.html', context)

@login_required
def list_board(request):
    board_members = Member.objects.filter(board_member=True)
    executive = {
        'president': 'Jan Schollenberger',
        'vice president': 'David Barnard',
        'secretary': 'Pam Berg',
        'treasurer': 'Craig Siegel',
        'past president': 'Mary Radtke Klein'
    }
    paginator = Paginator(board_members, 10)
    page_number = request.GET.get('page')
    members = paginator.get_page(page_number)
    context = {
        # 'executive': executive,
        'members': members,
    }
    return render(request, 'members/output.html', context)

@login_required
def list_active(request):
    # name1.split(' ')[-1]
    # REGEX \b(\w+)$
    active_members = Member.objects.filter(membership_status='Active')
    # members = Member.objects.filter(membership_status='active').order_by('name1')
    # members = Member.objects.filter(membership_status='active').extra(select={'lname1' : "SUBSTR(name1, -1 ,)"}).order_by('lname1')
    # print(members)
    paginator = Paginator(active_members, 10)
    page_number = request.GET.get('page')
    members = paginator.get_page(page_number)
    context = {
        'members': members,
    }
    return render(request, 'members/output.html', context)

@login_required
def list_inactive(request):
    inactive_members = Member.objects.filter(membership_status='Inactive')
    paginator = Paginator(inactive_members, 10)
    page_number = request.GET.get('page')
    members = paginator.get_page(page_number)
    context = {
        'members': members,
    }
    return render(request, 'members/output.html', context)

@login_required
def needs_review(request):
    needs_review = Member.objects.filter(needs_review=1)
    paginator = Paginator(needs_review, 10)
    page_number = request.GET.get('page')
    members = paginator.get_page(page_number)
    context = {
        'members': members,
    }
    return render(request, 'members/output.html', context)

@login_required
def search_results(request):
    querystring = request.GET['q']
    try:
        filter = request.GET['f']
    except:
        pass
    two_names_orig = querystring.split("and")
    # two_names_cleaned = [name for name in two_names if name.strip()]
    two_names = []
    for name in two_names_orig:
        two_names.append(name.strip())

    search_terms = querystring.split()
    search_terms = list(dict.fromkeys(search_terms))
    try:
        search_terms.remove('and')
    except:
        pass
    # print(search_terms)
    # print(two_names)

    member_records = Member.objects.all()
    try:
        print("Filter: {}".format(filter))
        member_records = member_records.filter(board_member=True)
    except:
        pass
    exact_match = member_records.filter(name1=querystring)
    members_name1_2n = member_records.filter(reduce(Q.__or__, [Q(name1__istartswith=word) for word in two_names])) # was icontains
    members_name2_2n = member_records.filter(reduce(Q.__or__, [Q(name2__istartswith=word) for word in two_names])) # was icontains
    members_name1_swst = member_records.filter(reduce(Q.__or__, [Q(name1__istartswith=word) for word in search_terms])) # was icontains
    members_name2_swst = member_records.filter(reduce(Q.__or__, [Q(name2__istartswith=word) for word in search_terms])) # was icontains
    members_name1_ewst = member_records.filter(reduce(Q.__or__, [Q(name1__iendswith=word) for word in search_terms])) # was icontains
    members_name2_ewst = member_records.filter(reduce(Q.__or__, [Q(name2__iendswith=word) for word in search_terms])) # was icontains
    members_name1_cst = member_records.filter(reduce(Q.__or__, [Q(name1__icontains=word) for word in search_terms]))
    members_name2_cst = member_records.filter(reduce(Q.__or__, [Q(name2__icontains=word) for word in search_terms]))
    # print(exact_match.exists())
    # print(members_name1.exists())
    # print(members_name2.exists())

    if exact_match.exists():
        context = {
            'members': exact_match,
            'querystring': querystring,
            'view': 'search_page',
            'match': '1:exact',
        }
        return render(request, 'members/output.html', context)
    elif members_name1_2n.exists() or members_name2_2n.exists():
        members = list(dict.fromkeys(chain(members_name1_2n, members_name2_2n)))
        context = {
            'members': members,
            'querystring': querystring,
            'view': 'search_page',
            'match': '2:pairs',
        }
        return render(request, 'members/output.html', context)
    elif members_name1_swst.exists() or members_name2_swst.exists():
        members = list(dict.fromkeys(chain(members_name1_swst, members_name2_swst)))
        context = {
            'members': members,
            'querystring': querystring,
            'view': 'search_page',
            'match': '2:swst',
        }
        return render(request, 'members/output.html', context)
    elif members_name1_ewst.exists() or members_name2_ewst.exists():
        members = list(dict.fromkeys(chain(members_name1_ewst, members_name2_ewst)))
        context = {
            'members': members,
            'querystring': querystring,
            'view': 'search_page',
            'match': '2:ewst',
        }
        return render(request, 'members/output.html', context)
    else:
        members = list(dict.fromkeys(chain(members_name1_cst, members_name2_cst)))
        context = {
            'members': members,
            'querystring': querystring,
            'view': 'search_page',
            'match': '3:words',
        }
        return render(request, 'members/output.html', context)

@login_required
def show_member_info(request, member_id):
    message = request.GET.get('message', '')
    member = Member.objects.filter(id=member_id)
    context = {
        'members': member,
        'message': message,
        'view': 'show_member_info_page',
    }
    return render(request, 'members/output.html', context)

@login_required
def edit_member_info(request, member_id):
    member = Member.objects.get(id=member_id)
    context = {
        'member': member,
    }
    return render(request, 'members/edit_member_info.html', context)

def save_member_info(request):
    member_id = request.POST['member_id']
    member_info = Member.objects.get(id=member_id)
    member_info.name1 = request.POST['name1'].strip()
    member_info.sort_by = request.POST['sort_by'].strip()
    member_info.byline = request.POST['byline'].strip()
    member_info.name2 = request.POST['name2'].strip()
    member_info.note = request.POST['note'].strip()
    member_info.address1 = request.POST['address1'].strip()
    member_info.address2 = request.POST['address2'].strip()
    member_info.city = request.POST['city'].strip()
    member_info.state = request.POST['state'].strip()
    member_info.postal_code = request.POST['postal_code'].strip()
    member_info.email1 = request.POST['email1'].strip()
    member_info.email2 = request.POST['email2'].strip()
    member_info.phone_number1 = request.POST['phone_number1'].strip()
    member_info.phone_number2 = request.POST['phone_number2'].strip()
    member_info.membership_status = request.POST['membership_status']
    member_info.membership_type = request.POST['membership_type']

    try:
        board_member = request.POST['board_member']
        if board_member == 'on':
            member_info.board_member = True
    except:
        member_info.board_member = False

    member_info.role = request.POST['role'].strip()

    try:
        directory_optout = request.POST['directory_optout']
        if directory_optout == 'on':
            member_info.directory_optout = True
    except:
        member_info.directory_optout = False

    try:
        needs_review = request.POST['needs_review']
        if needs_review == 'on':
            member_info.needs_review = True
    except:
        member_info.needs_review = False

    member_info.reason_for_review = request.POST['reason_for_review'].strip()
    member_info.save()

    return HttpResponseRedirect(reverse('members_app:show_member_info', kwargs={'member_id':member_id})+'?message=changes_saved')

members/templates/members/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>EAAC Members</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <link rel="shortcut icon" href="{{ STATIC_URL }}/static/favicon.png">
    <style media="screen" type="text/css">
      html, body {
        background: radial-gradient(#60A9EA, #6D6D6D);
        background-attachment: fixed;
        background-size: cover;
        box-sizing: border-box;
        margin: 0;
        padding: 0;
        width: 100%;
        height: 100%;
        font-size: 0.95em;
      }
      header {
        padding: 10px;
        background-color: #fff;
      }
      main {
        padding: 10px;
        margin: 20px auto;
      }
      /* main > * {
        box-shadow:           3px 3px 5px 0 rgba(25,25,25,0.4);
        -moz-box-shadow:      3px 3px 5px 0 rgba(25,25,25,0.4);
        -webkit-box-shadow:   3px 3px 5px 0 rgba(25,25,25,0.4);
      } */
      .main_edit {
        width: 90vw;
        /* height: 100vw; */
        padding: 10px;
        margin: 20px auto;
      }
      .pagination_top {
        border-radius: 10px 10px 0 0;
        /* text-align: center; */
      }
      .pagination_bottom {
        border-radius: 0 0 10px 10px;
        text-align: center;
      }
      .members_list_value {
        border: 1px solid #000;
        padding: 4px;
      }
      .members_list_header {
        border: 1px solid #000;
        padding: 4px;
        font-weight: bold;
      }
      .members_list {
        border-collapse: collapse;
        background-color: #fff;
      }
      .names_title {
        font-weight: bold;
      }
      .byline {
        font-style: italic;
        font-weight: normal;
      }
      .note {
        font-style: italic;
        font-weight: normal;
      }
      .tile {
        background-color: #fff;
        display: flex;
        flex-direction: row;
        align-items: flex-start;
        justify-content: flex-start;
      }
      .tile:first-child:last-child {
        border-radius: 10px;
      }
      .tile:first-child {
        border-radius: 10px 10px 0 0;
      }
      .tile:last-child {
        border-radius: 0 0 10px 10px;
      }
      .tile:nth-child(odd) {
        background-color: rgba(255,255,255,0.7);
      }
      .row {
        padding-right: 20px;
      }
      .col_ro {
        width: 400px;
      }
      .col_rw {
        width: 640px;
      }
      .container > * {
        padding: 10px;
        background-color: #fff;
      }
      .search_box {
        margin: 10px 0;
        width: 400px;
      }
      .red_label {
        color: red;
      }
      .needs_review {
        width: 220px;
      }
      .edit_link {
        margin: 10px 50px;
        color: blue;
        text-decoration: underline;
      }
      #clear_reason_lnk {
        font-size: 0.8em;
        text-decoration: none;
      }
      label {
        display: block;
        width: 230px;
        float: left;
        font-weight: bold;
      }
      .form_fields > input,
      .form_fields > select {
        width: 300px;
        margin-bottom: 10px;
      }
      h3 {
        background-color: #fff;
        margin: 0 auto;
        border-radius: 10px 10px 0 0;
      }
      .checkmark_bool_grid {
        text-align: center;
        font-size: 1.99em;
      }
      .submit_btn {
        text-align: center;
      }
      #filter_cb {
        margin-left: 5px;
      }
      .message {
        color: green;
        border-radius: 3px 3px 0 0;
        margin-left: 10px;
        padding: 2px 4px 2px 4px;
        background-color: #F2F2F2;
        /* z-index: 2; */
        /* text-transform: uppercase; */
      }
      #edit_member_form {
        border-radius: 0 0 10px 10px;
      }
      .execs {
        font-size: 1.2em;
      }
      #role_label, #role, #reason_for_review, #reason_for_review_label {
        visibility: hidden;
      }
    </style>
  </head>
    <body>
      <header>
        <h1>EAAC Members</h1>
        <div class="filter_members">Show:
          <input type="radio" name="filter_members" id="show_all"> <a href="/members/list_all/">All Members</a> ({{user.all_member_count}})
          <input type="radio" name="filter_members" id="show_board"> <a href="/members/list_board/">Board Members</a> ({{user.board_member_count}})
          <input type="radio" name="filter_members" id="show_active"> <a href="/members/list_active/">Active Members</a> ({{user.active_member_count}})
          <input type="radio" name="filter_members" id="show_inactive"> <a href="/members/list_inactive/">Inactive Members</a> ({{user.inactive_member_count}})
          <input type="radio" name="filter_members" id="show_needs_review"> <a href="/members/needs_review/">Needs Review</a> ({{user.needs_review_count}})
        </div>

          <input type="search" id="q" class="search_box" name="q" placeholder="&nbsp;Search for a Member" required>
          <button type="submit" class="" id="search_btn"><b>Search</b></button>
          <input type="checkbox" class="" name="filter_cb" id="filter_cb"/> Show Only Board Members
      </header>

      <main>
        {% block content %}{% endblock %}
      </main>

      <script type="text/javascript">
        let show_all = document.querySelector('#show_all');
        let show_board = document.querySelector('#show_board');
        let show_active = document.querySelector('#show_active');
        let show_inactive = document.querySelector('#show_inactive');
        let show_needs_review = document.querySelector('#show_needs_review');
        if (window.location.pathname == '/members/') {
          show_active.checked = true;
        } else if (window.location.pathname == '/members/list_all/') {
          show_all.checked = true;
        } else if (window.location.pathname == '/members/list_board/') {
          show_board.checked = true;
        } else if (window.location.pathname == '/members/list_active/') {
          show_active.checked = true;
        } else if (window.location.pathname == '/members/list_inactive/') {
          show_inactive.checked = true;
        } else if (window.location.pathname == '/members/needs_review/') {
          show_needs_review.checked = true;
        } else {
          show_all.checked = false;
          show_board.checked = false;
          show_active.checked = false;
          show_inactive.checked = false;
          show_needs_review.checked = false;
        }
        show_all.onclick = function() {
          window.location='/members/list_all/';
        }
        show_board.onclick = function() {
          window.location='/members/list_board/';
        }
        show_active.onclick = function() {
          window.location='/members/list_active/';
        }
        show_inactive.onclick = function() {
          window.location='/members/list_inactive/';
        }
        show_needs_review.onclick = function() {
          window.location='/members/needs_review/';
        }
      </script>

      <script type="text/javascript">
        search_btn = document.querySelector('#search_btn')
        q = document.querySelector('#q')
        filter_cb = document.querySelector('#filter_cb')
        search_btn.onclick = function(event) {
          if (q.value.trim() == '') {
            event.preventDefault()
          } else {
            if (filter_cb.checked) {
              window.location="{% url 'members_app:search_results' %}?q=" + q.value + "&f=board_only"
            } else {
              window.location="{% url 'members_app:search_results' %}?q=" + q.value
            }
          }
        }
        q.addEventListener("keydown", function (event) { // listen for  key presses
            if (event.keyCode === 13) {                                 // '13' is the Enter/Return key
                search_btn.click()                                      // emulate button click
            }
        })
      </script>

    </body>
  </html>

members/templates/members/grid.html
{% extends 'members/base.html' %}

{% block content %}

    <table class="members_list">
      <tr>
        <td class="members_list_header">Name(s)</td>
        <td class="members_list_header">Phone Number(s)</td>
        <td class="members_list_header">Address 1</td>
        <td class="members_list_header">Address 2</td>
        <td class="members_list_header">City</td>
        <td class="members_list_header">State</td>
        <td class="members_list_header">Postal Code</td>
        <td class="members_list_header">Email 1</td>
        <td class="members_list_header">Email 2</td>
        <td class="members_list_header">Membership Status</td>
        <td class="members_list_header">Type</td>
        <td class="members_list_header">Role</td>
        <td class="members_list_header">Directory Opt-Out</td>
        <td class="members_list_header">Needs Review</td>
        <td class="members_list_header">Reason for Review</td>
      </tr>
      {% for member in members %}
      <tr>
        <td class="members_list_value names_title">{{member.name1}}{% if member.byline != '' %}, <span class="byline">{{member.byline}}</span>{% endif %}{% if member.byline != '' and member.name2 != '' %},{% endif %}{% if member.name2 != '' %} and {% endif %} {{member.name2}}{% if member.note != '' %}<div class="note">{{member.note}}</div>{% endif %}</td>
        <td class="members_list_value">{{member.phone_number1}}{% if member.phone_number2 != '' %}<br>{{member.phone_number2}}{% endif %}</td>
        <td class="members_list_value">{{member.address1}}</td>
        <td class="members_list_value">{{member.address2}}</td>
        <td class="members_list_value">{{member.city}}</td>
        <td class="members_list_value">{{member.state}}</td>
        <td class="members_list_value">{{member.postal_code}}</td>
        <td class="members_list_value">{{member.email1}}</td>
        <td class="members_list_value">{{member.email2}}</td>
        <td class="members_list_value">{{member.membership_status|title}}</td>
        <td class="members_list_value">{{member.membership_type|title}}</td>
        <td class="members_list_value">{{member.role|title}}</td>
        <td class="members_list_value">{% if member.directory_optout %}<i class="bi bi-check"></i>{% endif %}</td>
        <td class="members_list_value checkmark_bool_grid">{% if member.needs_review %}<i class="bi bi-check"></i>{% endif %}</td>
        <td class="members_list_value">{{member.reason_for_review|title}}</td>
      </tr>
      {% endfor %}
    </table>
  </div>

{% endblock %}

members/templates/members/output.html
{% extends 'members/base.html' %}

{% block content %}

  <div class="container">
    <div class="pagination_top" style="background-color: #cde;">
        <span class="step-links" id="step_links_top">
            {% if members.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ members.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ members.number }} of {{ members.paginator.num_pages }}.
            </span>

            {% if members.has_next %}
                <a href="?page={{ members.next_page_number }}">next</a>
                <a href="?page={{ members.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% if executive %}
    <div class="execs">
        {% for key, value in executive.items %}
            <b>{{ key|title }}</b>: {{ value }}<br>
        {% endfor %}
    </div>
    {% endif %}
    {% for member in members %}
        <div class="tile">
          {% url 'members_app:needs_review' as needs_review_url %}
          {% if request.path == needs_review_url %}
          <div class="needs_review"><b>Needs Review</b>:<br><i>{{member.reason_for_review|title}}</i>
            <!-- <div class="edit_link"><a href="/members/edit_member_info/{{member.id}}/">Edit</a></div> -->
            <div class="edit_link"><a href="{% url 'members_app:edit_member_info' member.id %}">Edit</a></div>
          </div>
          {% endif %}
          <div class="col_ro">
            <div class="row">
              <span class="names_title">{{member.name1}}{% if member.byline %}<br><span class="byline">{{member.byline}}</span>{% endif %}{% if member.byline and member.name2 %}<br>{% endif %}{% if member.name2 %} and {{member.name2}}{% endif %}{% if member.note %}<div class="note">{{member.note}}</div>{% endif %}
            </div>
            <div class="row">
              {% if member.address1 != '' %}
              <div class="">{{member.address1}}</div>
              <div class="">{{member.address2}}</div>
              <div class="">{{member.city}}, {{member.state}} {{member.postal_code}}</div>
              {% endif %}
            </div>
            <div class="row">
              <div class="">{{member.email1}}</div>
              <div class="">{{member.email2}}</div>
            </div>
          </div>
          <div class="col_ro">
            <div class="row">
              <div class="">{% if member.phone_number1 %}{{member.phone_number1}}{% endif %}{% if member.phone_number2 %}, {{member.phone_number2}}{% endif %}</div>
              <!-- <div class="{% if member.membership_status == 'inactive' %}red_label{% endif %}">{{member.membership_status|title}} member</div> -->
              <div class="">{% if member.membership_type == 'PAM staff'%}{{member.membership_type}}{% else %}{{member.membership_type|title}}{% endif %}</div>
              <div>{% if member.board_member == True %}Board Member ({{member.role|title}}){% endif %}</div>
            </div>
          </div>
          {% url 'members_app:needs_review' as needs_review_url %}
          {% if request.path != needs_review_url %}
          <span><a href="{% url 'members_app:edit_member_info' member.id %}">edit</a></span>
          {% endif %}
        </div>
    {% endfor %}
    <div class="pagination_bottom">
        <span class="step-links" id="step_links_bottom">
            {% if members.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ members.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ members.number }} of {{ members.paginator.num_pages }}.
            </span>

            {% if members.has_next %}
                <a href="?page={{ members.next_page_number }}">next</a>
                <a href="?page={{ members.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
  </div>

  <script type="text/javascript">
  {% if view == 'search_page' %}
      document.getElementById("step_links_top").innerHTML = "Search Results for: <i><code>{{querystring}}</code></i>"
      document.getElementById("step_links_bottom").innerHTML = "";
      console.log('{{match}}')
  {% elif view == 'show_member_info_page' %}
        {% if message == "changes_saved" %}
          document.getElementById("step_links_top").innerHTML = "Changes Saved"
        {% else %}
          document.getElementById("step_links_top").innerHTML = "Member Details"
        {% endif %}
        document.getElementById("step_links_bottom").innerHTML = "";
    {% endif %}
  </script>

{% endblock %}